name: 'Terraform - Code Quality'

on:
  push:
    branches:
      - '**'
    paths:
      - 'PartIII/environments/**/*.tf'
      - 'PartIII/environments/**/*.tfvars'
      - '.github/workflows/terraform-checks.yml'
  pull_request:
    paths:
      - 'PartIII/environments/**/*.tf'
      - 'PartIII/environments/**/*.tfvars'
      - '.github/workflows/terraform-checks.yml'

jobs:
  terraform-checks:
    name: 'Terraform Checks'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"

    - name: Terraform Format Check
      run: terraform fmt -check -recursive
      
    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate